/** @module packages/pm-beads/extensions/beads/runtime-loader */
import { existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

/**
 * This file is auto-generated by scripts/gen-package-runtime-loaders.mjs.
 * Do not edit directly.
 */
const PM_PACKAGE_ROOT_ENV = "PM_CLI_PACKAGE_ROOT";
const CURRENT_EXTENSION_ROOT = path.dirname(fileURLToPath(import.meta.url));
const EXTENSION_NAME = "beads";
const PACKAGE_NAME = "pm-beads";
const DIAGNOSTIC_NAME = "beads";
/** Runtime module exports loaded from the installed package or co-located extension. */
export type PackageRuntimeModule = Record<string, unknown>;

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}

function isMissingRuntimeModuleError(error: unknown, modulePath: string): boolean {
  if (!isRecord(error) || error.code !== "ERR_MODULE_NOT_FOUND") {
    return false;
  }
  const moduleUrl = pathToFileURL(modulePath).href;
  if (error.url === moduleUrl) {
    return true;
  }
  if (typeof error.path === "string" && path.resolve(error.path) === path.resolve(modulePath)) {
    return true;
  }
  const message = typeof error.message === "string" ? error.message : "";
  const normalizedModulePath = modulePath.split("\\").join("/");
  return (
    message.startsWith(`Cannot find module '${modulePath}'`) ||
    message.startsWith(`Cannot find module '${normalizedModulePath}'`) ||
    message.startsWith(`Cannot find module '${moduleUrl}'`)
  );
}

// Node refuses to type-strip .ts files under node_modules
// (ERR_UNSUPPORTED_NODE_MODULES_TYPE_STRIPPING); fall through to the next
// candidate (the extension's co-located runtime.ts copy) instead of aborting.
function isUnstrippableTypeScriptError(error: unknown, modulePath: string): boolean {
  if (!isRecord(error)) {
    return false;
  }
  const message = typeof error.message === "string" ? error.message : "";
  if (error.code !== "ERR_UNSUPPORTED_NODE_MODULES_TYPE_STRIPPING" && !message.includes("Stripping types is currently unsupported")) {
    return false;
  }
  const moduleUrl = pathToFileURL(modulePath).href;
  const normalizedModulePath = modulePath.split("\\").join("/");
  return (
    error.url === moduleUrl ||
    (typeof error.path === "string" && path.resolve(error.path) === path.resolve(modulePath)) ||
    message.includes(modulePath) ||
    message.includes(normalizedModulePath) ||
    message.includes(moduleUrl)
  );
}

function resolvePackageRootCandidates(): string[] {
  const envRoot = process.env[PM_PACKAGE_ROOT_ENV];
  const candidates = typeof envRoot === "string" && envRoot.trim().length > 0 ? [path.resolve(envRoot.trim())] : [];
  const argvEntry = typeof process.argv[1] === "string" ? process.argv[1].trim() : "";
  if (argvEntry.length > 0) {
    const entryDir = path.dirname(path.resolve(argvEntry));
    candidates.push(path.resolve(entryDir, ".."));
    candidates.push(path.resolve(entryDir, "../.."));
    candidates.push(path.resolve(entryDir, "../../.."));
  }
  return [...new Set(candidates)];
}

function runtimePaths(packageRoot: string): string[] {
  return [
    path.join(packageRoot, ".agents", "pm", "extensions", EXTENSION_NAME, "runtime.ts"),
    path.join(packageRoot, "packages", PACKAGE_NAME, "extensions", EXTENSION_NAME, "runtime.ts"),
  ];
}

async function tryRuntime(modulePath: string, attempted: string[]): Promise<PackageRuntimeModule | undefined> {
  attempted.push(modulePath);
  if (!existsSync(modulePath)) {
    return undefined;
  }
  try {
    return await import(pathToFileURL(modulePath).href) as PackageRuntimeModule;
  } catch (error: unknown) {
    if (isMissingRuntimeModuleError(error, modulePath) || isUnstrippableTypeScriptError(error, modulePath)) {
      return undefined;
    }
    throw error;
  }
}

/** Resolve and load the first usable packaged runtime module. */
export async function loadPackageRuntimeModule(): Promise<PackageRuntimeModule> {
  const attempted: string[] = [];
  for (const modulePath of [...resolvePackageRootCandidates().flatMap(runtimePaths), path.join(CURRENT_EXTENSION_ROOT, "runtime.ts")]) {
    const loaded = await tryRuntime(modulePath, attempted);
    if (loaded) {
      return loaded;
    }
  }
  throw new Error(
    `Unable to resolve packaged ${DIAGNOSTIC_NAME} extension runtime module. ` +
      `Tried: ${attempted.join(", ")}. Ensure the installed extension includes runtime.ts or PM_CLI_PACKAGE_ROOT points to an installed pm package root.`,
  );
}
