/** @module packages/pm-todos/extensions/todos/runtime-loader */
import { existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

/**
 * This file is auto-generated by scripts/gen-package-runtime-loaders.mjs.
 * Do not edit directly.
 */
const PM_PACKAGE_ROOT_ENV = "PM_CLI_PACKAGE_ROOT";
const localRuntime = path.join(path.dirname(fileURLToPath(import.meta.url)), "runtime.ts");
/** Runtime module exports loaded from the installed package or co-located extension. */
export type PackageRuntimeModule = Record<string, unknown>;
const packageConfig = { extensionName: "todos", packageName: "pm-todos", diagnosticName: "todos" } as const;

const runtimeRoots = (): string[] => {
  const argvRoot = process.argv[1]?.trim()
    ? ["..", "../..", "../../.."].map((parent) => path.resolve(path.dirname(path.resolve(process.argv[1])), parent))
    : [];
  const candidates = [process.env[PM_PACKAGE_ROOT_ENV]?.trim(), ...argvRoot]
    .filter((root): root is string => Boolean(root))
    .map((root) => path.resolve(root));
  return [...new Set(candidates)];
};

const runtimeFiles = (): string[] => [
  ...runtimeRoots().flatMap((root) => [
    path.join(root, ".agents", "pm", "extensions", packageConfig.extensionName, "runtime.ts"),
    path.join(root, "packages", packageConfig.packageName, "extensions", packageConfig.extensionName, "runtime.ts"),
  ]),
  localRuntime,
];

const runtimeRecord = (value: unknown): Record<string, unknown> | undefined =>
  typeof value === "object" && value !== null ? value as Record<string, unknown> : undefined;

const isTargetMissing = (error: unknown, target: string): boolean => {
  const record = runtimeRecord(error);
  const targetUrl = pathToFileURL(target).href;
  const normalizedTarget = target.split("\\").join("/");
  const message = typeof record?.message === "string" ? record.message : "";
  return record?.code === "ERR_MODULE_NOT_FOUND" &&
    (record.url === targetUrl ||
      (record && typeof record.path === "string" && path.resolve(record.path) === path.resolve(target)) ||
      [target, normalizedTarget, targetUrl].some((value) => message.startsWith(`Cannot find module '${value}'`)));
};

// Node refuses to type-strip .ts files under node_modules; fall through to the
// next candidate (the extension's co-located runtime.ts copy) instead of aborting.
const isUnstrippable = (error: unknown, target: string): boolean => {
  const record = runtimeRecord(error);
  const message = typeof record?.message === "string" ? record.message : "";
  if (record?.code !== "ERR_UNSUPPORTED_NODE_MODULES_TYPE_STRIPPING" && !message.includes("Stripping types is currently unsupported")) {
    return false;
  }
  const targetUrl = pathToFileURL(target).href;
  const normalizedTarget = target.split("\\").join("/");
  return (
    record?.url === targetUrl ||
    (record && typeof record.path === "string" && path.resolve(record.path) === path.resolve(target)) ||
    [target, normalizedTarget, targetUrl].some((value) => message.includes(value))
  );
};

const loadRuntimeFile = async (target: string, attempted: string[]): Promise<PackageRuntimeModule | undefined> => {
  attempted.push(target);
  if (!existsSync(target)) {
    return undefined;
  }
  try {
    return await import(pathToFileURL(target).href) as PackageRuntimeModule;
  } catch (error: unknown) {
    if (isTargetMissing(error, target) || isUnstrippable(error, target)) {
      return undefined;
    }
    throw error;
  }
};

/** Resolve and load the first usable packaged runtime module. */
export async function loadPackageRuntimeModule(): Promise<PackageRuntimeModule> {
  const attempted: string[] = [];
  for (const target of runtimeFiles()) {
    const loaded = await loadRuntimeFile(target, attempted);
    if (loaded !== undefined) {
      return loaded;
    }
  }
  throw new Error(
    `Unable to resolve packaged ${packageConfig.diagnosticName} extension runtime module. ` +
      `Tried: ${attempted.join(", ")}. Ensure the installed extension includes runtime.ts or PM_CLI_PACKAGE_ROOT points to an installed pm package root.`,
  );
}
