import type { SearchOptions } from '@/types/index';

/** Build a complete deterministic option object while allowing focused test overrides. */
export function createTestSearchOptions(overrides: Partial<SearchOptions> = {}): SearchOptions {
  const defaults: SearchOptions = {
    query: 'test query',
    format: 'toon',
    engines: null,
    lang: null,
    page: 1,
    safeSearch: 0,
    timeRange: null,
    category: null,
    limit: 10,
    timeout: 15000,
    verbose: false,
    output: null,
    unescape: true,
    autoformat: true,
    score: false,
    interactive: false,
    noCache: false,
    retries: 2,
    open: null,
    stats: false,
    raw: false,
    filter: null,
    batch: null,
    bookmark: null,
    export: null,
    quick: false,
    summary: false,
    dedup: true,
    sort: false,
    group: null,
    config: null,
    showInfo: false,
    runTest: false,
    preset: null,
    savePreset: null,
    listPresets: false,
    compare: null,
    cluster: null,
    suggestions: false,
    pipe: false,
    stream: false,
    jsonl: false,
    rank: false,
    multiSearch: null,
    domainFilter: null,
    excludeDomain: null,
    minScore: null,
    hasImage: false,
    dateAfter: null,
    dateBefore: null,
    theme: 'default',
    compact: false,
    metadata: false,
    urlsOnly: false,
    titlesOnly: false,
    autocomplete: false,
    proxy: null,
    insecure: false,
    health: false,
    watch: false,
    silent: false,
    pretty: false,
    confirm: false,
    agent: false,
    analyze: false,
    cacheStatus: false,
    extract: null,
    sentiment: false,
    structured: false,
    citation: false,
    rawContent: false,
    exportEmbeddings: false,
    autoRefine: false,
    fetchContent: false,
    systemPrompt: null,
    validateOutput: false,
    strict: false,
    offlineFirst: false,
    requestJson: false,
    refreshEngines: false,
    instanceInfo: false,
    instanceInfoJson: false,
    searxngParams: undefined,
    estimateTokens: false,
    maxTokens: null,
  };

  for (const [key, value] of Object.entries(overrides) as [
    keyof SearchOptions,
    SearchOptions[keyof SearchOptions],
  ][]) {
    if (value !== undefined) Object.assign(defaults, { [key]: value });
  }
  return defaults;
}
